# Generated by Django 3.0.5 on 2020-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('location_shoot', models.IntegerField()),
                ('print_credit', models.IntegerField()),
                ('digital_files', models.IntegerField()),
            ],
        ),
    ]
